### ISSUE TITLE
fileAccess() changes the .Random.seed

### ISSUE THREAD

**Issue by greglzmayer** [HenrikBengtsson/R.utils#104]
When checking for writeable access to a directory by calling `fileAccess(dir, mode=2)`, the `.Random.seed` is changed.  This is unexpected from the user's perspective.

For example:
```
old.seed <- .Random.seed
res <- fileAccess("/usr/local", mode=2)
print(identical(old.seed, .Random.seed))
# [1] FALSE
```

Changing
```
setMethodS3("fileAccess", "default", function(pathname, mode=0, safe=TRUE, ...) {
  ...
        repeat {
          chars <- sample(c(base::letters, base::LETTERS), size=n)
          filename <- paste(chars, collapse="")
          pathname <- file.path(path, filename)
          if (!file.exists(pathname))
            break
          pathname <- NULL
        }
  ...
}
```
to

```
setMethodS3("fileAccess", "default", function(pathname, mode=0, safe=TRUE, ...) {
  ...
        withSeed({
          repeat {
            chars <- sample(c(base::letters, base::LETTERS), size=n)
            filename <- paste(chars, collapse="")
            pathname <- file.path(path, filename)
            if (!file.exists(pathname))
              break
            pathname <- NULL
          }
        }, NULL)
  ...
}
```
would prevent the function from modifying the RNG state.

**Comment by HenrikBengtsson** [comment]
Totally agree. Thanks for spotting this. In the same vein as `withSeed()` I might add a "stealth" sampler that I'm using elsewhere:

https://github.com/HenrikBengtsson/future/blob/661e253eb1eb28aa1699a3190d907213819741d5/R/utils.R#L318-L329


FWIW, I have a task callback handler set in my `~/.Rprofile` so that I get a warning whenever .Random.seed is updated.  It has helped me narrow down a few of these.
```r
rng_tracker <- local({
  last <- .GlobalEnv$.Random.seed
  function(...) {
    curr <- .GlobalEnv$.Random.seed
    if (!identical(curr, last)) {
      warning(".Random.seed changed", call. = FALSE, immediate. = TRUE)
      last <<- curr
    }
    TRUE
  }
})

invisible(addTaskCallback(rng_tracker, name = "RNG tracker"))
```

```r
> sample(1)
[1] 1
Warning: .Random.seed changed
> future:::stealth_sample(1)
[1] 1
> sample(1)
[1] 1
Warning: .Random.seed changed
```

**Comment by HenrikBengtsson** [comment]
I'm working on this but just a quick comment; I was intrigued by your `withSeed(..., seed = NULL)` solution.  I've missed that `set.seed(NULL)` resets and sets `.Random.seed`.  Unfortunately, it turns out this feature was added to R 3.0.0 and R.utils supports R (>= 2.14.0).  I might ending up introducing backward-compatible support for `seed = NULL` in `withSeed()`.

**Comment by HenrikBengtsson** [comment]
This has now been fixed in the develop version.  I ended up adding support for `withSeed(..., seed = NULL)` also for R (< 3.0.0) + a few other tweaks to `fileAccess()`.  Thanks again for reporting.
