### ISSUE TITLE
Error : object ‘clone’ is not exported by 'namespace:R.oo'

### ISSUE THREAD

**Issue by mattdowle** [HenrikBengtsson/R.utils#29]
This is a similar problem to #28 .  The solution there helped me track it down - thanks.  My .Rprofile loads package `bit64` which loads `bit`, which exports `clone`.

Reinstalling `R.oo` as follows : 

```
R --vanilla
install.packages("R.oo")
```

Then allowed me to `install.packages("R.utils")` with or without `bit` loaded.

My question is why is this necessary?  Is this due to recent changes in R?  Never seen it before.

Further, object `clone` is indeed exported by R.oo it seems,  so why does the error message say it is not exported ?

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  grDevices datasets  stats     utils     methods   base     

other attached packages:
[1] bit64_0.9-5 bit_1.1-12 
```

**Comment by HenrikBengtsson** [comment]
Hi. Nothing due to changes in R.  This is the "fault" of `R.methodsS3::setMethodS3()` which is used to setup S3 method and S3 generic functions.  I created a separate Issue HenrikBengtsson/R.methodsS3#3 to patch/fix this.  This problem may occur when both:
* a conflicting package is attach already on startup, e.g. in `.Rprofile`, and
* a package using `R.methodsS3::setMethodS3()` is installed _from source_.

It never occurs if one installs from a binary build (e.g. OS X or Windows) and never if `.Rprofile` does not attach a package.

# Reproducible example

## Attaching conflicting package on startup [BAD]
Add `library(bit)` to `~/.Rprofile`.  Then start R to see:
```r
> install.packages("R.oo", type="source")
[...]
> R.oo::clone
Error: 'clone' is not an exported object from 'namespace:R.oo'
```
This means failure.

## Not-attaching conflicting package on startup [OK]
Remove `library(bit)` from `~/.Rprofile` and start R:
```r
> R.oo::clone
function (...)
UseMethod("clone")
<environment: namespace:R.oo>
attr(,"export")
[1] TRUE
```
This means success.

## Attaching conflicting package before installing [OK]
If not attached `bit` on startup, but manually does not seem to be a problem:
```r
> library(bit)
[...]
> install.packages("R.oo", type="source")
[...]
> R.oo::clone
function (...)
UseMethod("clone")
<environment: namespace:R.oo>
attr(,"export")
[1] TRUE
```
Thus, no problem.

## R --vanilla still attaches conflicting package at installation [BAD]
FYI, if keep `library(bit)` in `.Rprofile` and use `R --vanilla` on Windows, I still get that `bit` is attached _when R.oo is installed_, e.g.
```r
> install.packages("R.oo", type="source")
Installing package into 'C:/Users/hb/R/win-library/3.2'
(as 'lib' is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.rstudio.com/src/contrib/R.oo_1.19.0.tar.gz'
Content type 'application/x-gzip' length 401147 bytes (391 KB)
downloaded 391 KB

Attaching package bit
package:bit (c) 2008-2012 Jens Oehlschlaegel (GPL-2)
creators: bit bitwhich
coercion: as.logical as.integer as.bit as.bitwhich which
operator: ! & | xor != ==
querying: print length any all min max range sum summary
bit access: length<- [ [<- [[ [[<-
for more help type ?bit

Attaching package: 'bit'

The following object is masked from 'package:base':

    xor

* installing *source* package 'R.oo' ...
** package 'R.oo' successfully unpacked and MD5 sums checked
[...]
```
which results in the same error:
```r
> R.oo::clone
Error: object 'clone' not found whilst loading namespace 'R.oo'
```

The fact that `install.packages()` loads `.Rprofile` in its separate R session used solely for the installation regardless whether R itself was launched with `--vanilla` or not is problematic and confusing.  I would be in favor the spawn installation R session could inherit the arguments from the main R session.  FYI, I've already reported to R devel on another issue related to this behavior: https://stat.ethz.ch/pipermail/r-devel/2014-December/070277.html

# Background
The quick background is that `setMethodS3()` was designed before namespaces were supported in R - all we had were attached packages on the `search()` path.  Sometimes new functions were added to core R or dependent package that would introduce another clash.  At that time there was no good way to protect against name clashes and overridden function.  The `setMethodS3()` tried to protect against the most common clashes by reusing existing generic functions if they already existed etc.  It simply tries to be agile to the setup of the user without the developer having to tweak the package for every possible scenario and R version etc.  What you are experience is when this strategy is now going against you/us:

1. Package `bit` is attached, which exports a `clone()` function.
2. When you install `R.oo` _from source_, the package
  1. calls `setMethodS3("clone", "Object", function(...) { })` to setup S3 method `clone()` for class `Object`.  So far so good.
  2. It then also check whether there is a need for a generic function `clone()`.  It search the R session for such a generic function and finds one - `bit::clone()`.  It concludes it doesn't need to create its own but can reuse that one.
  3. Package is installed, but `R.oo::clone` does not exist.
3. Later, when you load/attach `R.utils`, it tries to explicitly import `R.oo::clone` (because it has an [`importFrom("R.oo", "clone")` statement in its NAMESPACE file](https://github.com/HenrikBengtsson/R.utils/blob/master/NAMESPACE#L24)).  It is in this step the error is generated.
Thus, the error is because R.oo is not installed correctly, but it only reveals itself when R.utils tries to load.

One idea is to make `setMethodS3()` more clever about where it should check for generic functions, because clearly `bit` is not part of its dependent packages but it still allows itself to be agile to it.  This was a good strategy R's pre-namespace era, but not as good anymore.  Further work will take place in Issue HenrikBengtsson/R.methodsS3#3.

**Comment by mattdowle** [comment]
Many thanks. Awesome answer.  I still come back here whenever R.oo is updated, as it was on 1 Nov 2016.

**Comment by HenrikBengtsson** [comment]
Hehe and perfect timing catching me in my jet lag window - you've got 110℅ of my attention right now. I'll at least fix the clone() function, cf. HenrikBengtsson/R.oo#17.

**Comment by HenrikBengtsson** [comment]
This has now been fixed in the next version of R.oo, cf. HenrikBengtsson/R.oo#17.  Thanks.

**Comment by mattdowle** [comment]
Awesome!  Party!
Thanks, Matt

**Comment by mattdowle** [comment]
Fantastic.  Thanks!
