### ISSUE TITLE
negative numbers in cmdArgs()

### ISSUE THREAD

**Issue by ilmarijuutilainen** [HenrikBengtsson/R.utils#31]
My command may have negative  decimal numbers as command line arguments, like ‘Rscript my_script.R -u4 -0.02 -u5 -0.015’. In the new version (2.1.0) cmdArgs() function parse result is u4=TRUE, u5=TRUE. In earlier version (1.27.1) it was u4=-0.02, u5=-0.015. Seems to be a bug in the new version.

**Comment by HenrikBengtsson** [comment]
The solution is to use <name>=<value> arguments, e.g.
```r
$ Rscript -e "str(R.utils::cmdArgs())" -u4=-0.02 -u5=-0.015
List of 2
 $ u4: num -0.02
 $ u5: num -0.015

$ Rscript -e "str(R.utils::cmdArgs())" u4=-0.02 u5=-0.015
List of 2
 $ u4: num -0.02
 $ u5: num -0.015
```

# Details
I can reproduce what you're reporting:

## R.utils (<= 1.32.4) (May 2014)
```r
$ Rscript -e "str(R.utils::cmdArgs())" -a -0.1 -b -1.0 -c -1 -d -1. -f 1
List of 6
 $ a: num -0.1
 $ b: num -1
 $ c: logi TRUE
 $ 1: logi TRUE
 $ d: num -1
 $ f: int 1
```

## R.utils (>= 1.33.0) (Aug 2014) including R.utils 2.1.0 (May 2015)
```r
$ Rscript -e "str(R.utils::cmdArgs())" -a -0.1 -b -1.0 -c -1 -d -1. -f 1
List of 6
List of 9
 $ a  : logi TRUE
 $ 0.1: logi TRUE
 $ b  : logi TRUE
 $ 1.0: logi TRUE
 $ c  : logi TRUE
 $ 1  : logi TRUE
 $ d  : logi TRUE
 $ 1. : logi TRUE
 $ f  : int 1
```

The change was introduced in R 1.33.0 (Aug 2014) probably due to the following [NEWS entry](https://github.com/HenrikBengtsson/R.utils/blob/master/NEWS#L179-L180):
```
o BUG FIX: commandArgs() would drop command-line arguments with periods,
  hyphens, or underscores in their names, e.g. --src_file=x.
```
The following example illustrates what the bug was prior to R.utils 1.33.0:
```r
$ Rscript -e "str(R.utils::cmdArgs())" -ab 1 -a_b 2 -a.b 3
List of 5
 $ ab  : int 1
 $ -a_b: logi NA
 $ 2   : logi NA
 $ -a.b: logi NA
 $ NA  : int 3
```
and after the fix we get:
```r
$ Rscript -e "str(R.utils::cmdArgs())" -ab 1 -a_b 2 -a.b 3
List of 3
 $ ab : int 1
 $ a_b: int 2
 $ a.b: int 3
```
This indicates that what you used was actually a feature that was not intended.

Hope this helps.

**Comment by HenrikBengtsson** [comment]
Should have rounded off showing how the `<name>=<value>` makes things clearer:
```r
$ Rscript -e "str(R.utils::cmdArgs())" -a=-0.1 -b=-1.0 -c=-1 -d=-1. -f=1
List of 5
 $ a: num -0.1
 $ b: num -1
 $ c: int -1
 $ d: num -1
 $ f: int 1
```
