### ISSUE TITLE
R.utils::GString ability of "[function] call"  does not seem to be working (anymore?).

### ISSUE THREAD

**Issue by AndreMikulec** [HenrikBengtsson/R.utils#32]
I can not get GString ability of "[function] call" to work.

# After I run . . .

library(R.Utils)

options(width=255)
cat(as.character(GString("(x,y)=(${x},$[capitalize]{y})")), sep=", ");cat("\n")

# My output is this . . . world and hello are not getting capitalized

(x,y)=(1,hello), (x,y)=(2,world), (x,y)=(3,hello), (x,y)=(4,world), (x,y)=(5,hello) # # HERE - why not H(cap)ello

# Am I doing something wrong?

# Is there a (quick or not-quick) work-around?

Thanks,
Andre Mikulec

**Comment by HenrikBengtsson** [comment]
Thanks for reporting; here's a smaller example of what you're reporting on:
```r
> library(R.utils)
> y <- "hello"
> as.character(GString("${y} => $[capitalize]{y}"))
[1] "hello => hello"
```
I'll look into this.

**Comment by HenrikBengtsson** [comment]
Fixed. You can try by installing the 'develop' version as:
```r
source('http://callr.org/install#HenrikBengtsson/R.utils@develop')
```
You should then get:
```r
> library(R.utils)
> y <- "hello"
> as.character(GString("${y} => $[capitalize]{y}"))
[1] "hello => Hello"
> as.character(GString("${y} => $[toupper]{y}"))
[1] "hello => HELLO"
```

**Comment by HenrikBengtsson** [comment]
@AndreMikulec, I recommend you to look at the [R.rsp](https://cran.r-project.org/package=R.rsp) package, which implements the RSP markup language.  It'll allow you to do much more powerful things.

For instance, the `as.character(GString("${y} => $[capitalize]{y}"))` example can be done as:
```r
> library(R.rsp)
> y <- "hello"
> rstring("<%=y%> => <%=capitalize(y)%>")
[1] "hello => Hello"
```
There will be differences though, e.g. vectors are handled differently.  But still, have a look at R.rsp, because it's really powerful.

**Comment by AndreMikulec** [comment]
Thanks.  That works now.  I will look seriously at R.rsp.

**Comment by vapniks** [comment]
I need GString for building excel formulas with XLConnect. R.rsp is no good for that because it doesn't handle vectors in the same way. 
Looking at the code for `evaluate.GString` it seems unfinished; it matches "${..}" but not "$[...]{}" at the beginning, and there's this weird assignment a few lines later: "...abcdef <- TRUE"
I'm going to have a go at debugging this, and any tips would be most appreciated.

**Comment by vapniks** [comment]
Just submitted a patch to fix this. It was a simple regexp error.

**Comment by HenrikBengtsson** [comment]
Thanks. I'll look into this (testing, revdep checks etc). as soon as I've got time.
