### ISSUE TITLE
sourceDirectory() stops working on environment clear

### ISSUE THREAD

**Issue by mattpolicastro** [HenrikBengtsson/R.utils#52]
If you remove all objects from the global environment (`rm(list = ls())` or RStudio's "clear" button), `sourceDirectory` appears to stop working until a new session is started. This is problematic when performing initial cleanup in scripts or Rmarkdown documents. 

**Steps to Reproduce**
```
>  R.utils::sourceDirectory("test")
>  test_func() # defined inside test/test_func.R as `function() { message("Test worked") }`
Test worked
>  rm(list = ls())
>  R.utils::sourceDirectory("test") # re-import the directory
>  test_func() # try the test func again
Error: could not find function "test_func"
```

I'm working inside a packrat directory and am on OS X, for what it's worth.

**Comment by HenrikBengtsson** [comment]
Hi, thanks for the feedback.

The reason for this is that the default for `sourceDirectory()` is `modifiedOnly=TRUE`.  With `sourceDirectory(..., modifiedOnly=TRUE)` only files that has not been sources previously or files that have been updated/modified since last call to `sourceDirectory()` will be `source()`:ed.  So, the second time your call the function, it decides that none of the files have changed so it will simply just skip all of them.  The solution for you in this case is to call:
```r
R.utils::sourceDirectory("test", modifiedOnly=FALSE)
```

When this was designed, I went back and fourth trying to decide what the default should be, but after realizing that I nearly always called `sourceDirectory(..., , modifiedOnly=TRUE)` myself, [I decided to make that the new default](https://github.com/HenrikBengtsson/R.utils/blob/master/NEWS#L325-L328) about two years ago.

I could consider making the default an option, e.g. `modifiedOnly=getOption("R.utils.modifiedOnly", TRUE)`, if that would be helpful.

**Comment by mattpolicastro** [comment]
Ah! Thank you for clarifying. I'm inclined toward what seems like the more transparent behaviour—sourcing all files by default—but your decision makes sense to me. Perhaps a small addition to the Description/Details fields in the documentation to express this more explicitly? 

Regardless, this is definitely my own error and no need to make breaking changes. Thanks for the great package!
