### ISSUE TITLE
`compressFile` deleting input file by default is a suprising behavior

### ISSUE THREAD

**Issue by dracodoc** [HenrikBengtsson/R.utils#66]
Even if I read the document and noticed the `remove = TRUE` behavior before, it still took me some time to really realize my input file have been deleted after some code. 

I'm not sure about the reasoning of this default behavior. If you change the default to FALSE, will it break any current code? If not, I would strongly suggest to change it.

**Comment by HenrikBengtsson** [comment]
Thanks for the feedback.  The reason for `remove = TRUE` is for `R.utils::gzip()` to emulate the behavior of command-line `gzip` calls.  Although it might not break existing code if `remove = FALSE` would become the default, it's likely to make existing pipelines leave large uncompressed files behind.

I'm choosing not to change the default, because this goes really far + the emulation argument.  Note also that the input file is only deleted if the output file is created - the operation is as "atomic" as possible - so no half written files are produced.
