### ISSUE TITLE
decompressFile doesn't need to separate between gzfile and bzfile

### ISSUE THREAD

**Issue by xhdong-umd** [HenrikBengtsson/R.utils#68]
According to `?connections`:

>For reading, the type of compression (if any) can be determined from the first few bytes of the file. Thus for file(raw = FALSE) connections, if open is "", "r" or "rt" the connection can read any of the compressed file types as well as uncompressed files. (Using "rb" will allow compressed files to be read byte-by-byte.) Similarly, gzfile connections can read any of the forms of compression and uncompressed files in any read mode.

This means we don't really need to create functions to use gzfile and bzfile separately. gzfile can handle them all. To compress file with specific format there is need for `gzip` and `bzip2` separately, but there is no need for `gunzip` and `bunzip2`.

**Comment by HenrikBengtsson** [comment]
Thanks for the feedback.  I think I'm using `gzfile()` connection feature elsewhere in my software stack and it's pretty neat.  

If I understand your comment, it consists of two parts.  One is that instead of `bunzip2()` calling `decompressFile()` with `FUN = bzfile` it could equally well do it with `FUN = gzfile`.  
Sure that would work.  The downside would be that it would have to be explained, otherwise another developer/user would wonder if that is a cut'n'paste typo.  BTW, a feature that one gets by using `bzfile()` is that it will (I think) produce an error if the compression used is not GZIP, which in turn made me realize that the same cannot be done for asserting that GZIP was used.

The second part is that `bunzip2()` doesn't even have to exist, because `gunzip()` would achieve the same thing.  Although this is true, I think it's convenient to export a `bunzip2()` because that is what a user might look for when they have a `*.bz2` they need to decompress from within R.
