### ISSUE TITLE
intToBin(x) = NA, if x>=2^31

### ISSUE THREAD

**Issue by mjhalwa** [HenrikBengtsson/R.utils#71]
for `x>= 2^31`, `as.integer(x)` returns an `NA`, where `as.numeric(x)` would not ... though this would not check for a non-floating point value. 
In addition, `as.character(x)` generates a warning message for `x >= 2^54`

> Warning message:
> probable complete loss of accuracy in modulus

Any ideas? I now try to divide `x >= 2^31` into `2^30` chunks, evaluate each invidually and concatenate afterwards.

**Comment by HenrikBengtsson** [comment]
Thanks.

Turns out that it is possible to extend `intToBin()` to supports values outside of [-2^31, +2^31] (R's integer range).  The same is _not_ possible for `intToHex()` and `intToOct()`.  The develop version of R.utils has been updated.  See https://github.com/HenrikBengtsson/R.utils how to install.

**Comment by HenrikBengtsson** [comment]
I have to revert this change (luckily it never reached CRAN).  The reason for the range limit [-2^31,2^31] (R's integer range) is such that we can also represent negative values, e.g. `intToHex(-1)` == `"ffffffff"`.  This is related to Issue #78.
